const { Router } = require("express");
const authRoutes = require("./auth.routes");
const systemAdminRoutes = require("./systemAdmin.routes");
const promoterRoutes = require("./promoter.routes");
const locationAdminRoutes = require("./locationAdmin.routes");
const apartmentAdminRoutes = require("./apartmentAdmin.routes");
const residentRoutes = require("./resident.routes");
const staffRoutes = require("./staff.routes");
const complaintRoutes = require("./complaint.routes");
const visitorRoutes = require("./visitor.routes");
const amenityRoutes = require("./amenity.routes");
const financeRoutes = require("./finance.routes");
const notificationRoutes = require("./notification.routes");
const emergencyRoutes = require("./emergency.routes");
const marketplaceRoutes = require("./marketplace.routes");
const deliveryRoutes = require("./delivery.routes");
const petRoutes = require("./pet.routes");
const surveyRoutes = require("./survey.routes");
const helpdeskRoutes = require("./helpdesk.routes");
const moveRoutes = require("./move.routes");
const membershipRoutes = require("./membership.routes");
const communityTalentRoutes = require("./communityTalent.routes");

const router = Router();

router.use("/auth", authRoutes);
router.use("/system-admin", systemAdminRoutes);
router.use("/promoter", promoterRoutes);
router.use("/location-admin", locationAdminRoutes);
router.use("/apartment-admin", apartmentAdminRoutes);
router.use("/resident", residentRoutes);
router.use("/staff", staffRoutes);
router.use("/complaints", complaintRoutes);
router.use("/visitors", visitorRoutes);
router.use("/amenities", amenityRoutes);
router.use("/finance", financeRoutes);
router.use("/notifications", notificationRoutes);
router.use("/emergency", emergencyRoutes);
router.use("/marketplace", marketplaceRoutes);
router.use("/delivery", deliveryRoutes);
router.use("/pets", petRoutes);
router.use("/surveys", surveyRoutes);
router.use("/helpdesk", helpdeskRoutes);
router.use("/move", moveRoutes);
router.use("/memberships", membershipRoutes);
router.use("/community-talent", communityTalentRoutes);

module.exports = router;
